'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import confetti from 'canvas-confetti';
import { Check, Copy, Music2, QrCode, Radio, Sparkles, Users, X } from 'lucide-react';
import { Logo } from '@/components/ui/Logo';
import { Button } from '@/components/ui/Button';
import { useGameState, useNow } from '@/hooks/useGameState';
import { apiFetch } from '@/lib/api';
import { avatarEmoji, formatMode } from '@/lib/utils';
import { Leaderboard } from './Leaderboard';
import { playTone } from '@/lib/sounds';

export function HostGame({code}:{code:string}){
  const{state,loading,error,refresh}=useGameState(code);const now=useNow();const[actionError,setActionError]=useState('');const[origin,setOrigin]=useState('');const actionKey=useRef('');const revealKey=useRef('');
  useEffect(()=>setOrigin(window.location.origin),[]);
  const seconds=state?.round?.answer_deadline?Math.max(0,Math.ceil((new Date(state.round.answer_deadline).getTime()-now)/1000)):0;
  const revealSeconds=state?.round?.reveal_ends_at?Math.max(0,Math.ceil((new Date(state.round.reveal_ends_at).getTime()-now)/1000)):0;
  useEffect(()=>{if(!state?.round)return;const round=state.round;if(round.status==='answering'&&seconds===0){const key=`resolve-${round.id}`;if(actionKey.current!==key){actionKey.current=key;apiFetch(`/api/games/${code}/resolve`,{method:'POST'}).then(()=>void refresh()).catch(()=>setTimeout(()=>{actionKey.current='';void refresh()},800));}}if(round.status==='revealed'&&revealSeconds===0){const key=`next-${round.id}`;if(actionKey.current!==key){actionKey.current=key;apiFetch(`/api/games/${code}/next`,{method:'POST'}).then(()=>void refresh()).catch(()=>setTimeout(()=>{actionKey.current='';void refresh()},800));}}},[state?.round,seconds,revealSeconds,code,refresh]);
  useEffect(()=>{if(state?.round?.status==='revealed'&&revealKey.current!==state.round.id){revealKey.current=state.round.id;playTone('scan');const exact=state.round.answers?.filter(a=>a.is_exact).length??0;if(exact>0)confetti({particleCount:100+exact*12,spread:80,origin:{y:.62}});}},[state?.round]);
  const allReady=Boolean(state?.players.length&&state.players.length>=2&&state.players.every(p=>p.ready));
  async function start(){try{setActionError('');await apiFetch(`/api/games/${code}/start`,{method:'POST'});}catch(e){setActionError(e instanceof Error?e.message:'No se pudo iniciar.')}}
  if(loading)return <LoadingStage/>;
  if(error||!state)return <ErrorStage message={error||'No se pudo abrir la partida.'}/>;
  if(state.game.status==='waiting')return <Lobby state={state} origin={origin} allReady={allReady} onStart={start} error={actionError}/>;
  if(state.game.status==='finished')return <Finish state={state}/>;
  return <div className="gamePage" data-game-theme={state.game.theme}><header className="gameHeader"><Logo/><div className="gameStats"><Stat label="Ronda" value={`${state.game.current_round}/${state.game.total_rounds}`}/><Stat label="Restantes" value={Math.max(0,state.game.total_rounds-state.game.current_round)}/><Stat label="Tiempo" value={state.round?.status==='answering'?`${seconds}s`:state.round?.status==='revealed'?`${revealSeconds}s`:'—'}/><Stat label="Jugadores" value={state.players.length}/></div><div className="gameCode">{state.game.code}</div></header><main className="gameMain"><section className="stage glass">{state.round?.status==='waiting_scan'&&<WaitingScan round={state.round.round_number} scanUrl={state.round.scan_url}/>} {state.round?.status==='answering'&&<Answering seconds={seconds} responses={state.round.response_count} total={state.players.length}/>} {state.round?.status==='revealed'&&state.round.song&&<Reveal round={state.round} seconds={revealSeconds}/>}</section><Leaderboard players={state.players}/></main></div>
}
function Stat({label,value}:{label:string;value:React.ReactNode}){return <div className="gameStat"><small>{label}</small><strong>{value}</strong></div>}
function Lobby({state,origin,allReady,onStart,error}:{state:NonNullable<ReturnType<typeof useGameState>['state']>;origin:string;allReady:boolean;onStart:()=>void;error:string}){const joinUrl=`${origin}/join?code=${state.game.code}`;return <div className="gamePage" data-game-theme={state.game.theme}><header className="gameHeader"><Logo/><div className="gameStats"><Stat label="Modo" value={formatMode(state.game.mode)}/><Stat label="Rondas" value={state.game.total_rounds}/><Stat label="Tiempo" value={`${state.game.time_limit}s`}/><Stat label="Jugadores" value={`${state.players.length}/${state.game.max_players}`}/></div><div className="gameCode">LOBBY</div></header><main className="lobbyStage"><section className="lobbyCode glass"><span className="eyebrow">Únete desde tu celular</span><h1>{state.game.code}</h1><div className="lobbyQr"><QRCodeSVG value={joinUrl||state.game.code} size={190} bgColor="#fff" fgColor="#080911" level="M"/></div><p style={{color:'var(--muted)',margin:'0 0 18px'}}>Escanea este QR o entra a RitmoLínea y escribe el código.</p><Button variant="ghost" onClick={()=>{navigator.clipboard.writeText(joinUrl);playTone('click')}}><Copy size={17}/>Copiar enlace</Button></section><section className="playersGrid glass"><div className="pageHead"><div><span className="eyebrow">Sala en vivo</span><h2 style={{margin:'8px 0'}}>Jugadores</h2></div><Radio color="var(--success)"/></div><div className="playersGridInner">{state.players.map(p=><div className={`playerTile ${p.ready?'ready':''}`} key={p.id}><span className="emoji">{avatarEmoji(p.avatar_id)}</span><div><strong>{p.name}</strong><small>{p.ready?'Listo para jugar':'Preparándose...'}</small></div></div>)}{state.players.length===0&&<p style={{color:'var(--muted)'}}>Esperando al primer jugador...</p>}</div><div style={{marginTop:22}}>{error&&<div className="errorBox" style={{marginBottom:12}}>{error}</div>}<Button className="buttonFull buttonBig" disabled={!allReady} onClick={onStart}>{allReady?<><Sparkles/>Todos listos · iniciando</>:<><Users/>Esperando jugadores listos</>}</Button><small style={{display:'block',color:'var(--muted)',textAlign:'center',marginTop:10}}>La partida también comienza automáticamente cuando todos estén listos.</small></div></section></main></div>}
function WaitingScan({scanUrl,round}:{scanUrl?:string;round:number}){return <><div className="stageGlow"/><div className="record"/><div className="stageStatus"><span className="eyebrow">Ronda {round}</span><h2>Escanea para soltar el beat</h2><p>Usa el teléfono conectado al parlante. Spotify se abrirá automáticamente.</p></div>{scanUrl&&<div className="qrPanel"><QRCodeSVG value={scanUrl} size={132} fgColor="#080911"/><small><QrCode size={14} style={{verticalAlign:'middle'}}/> DJ · ESCANEAR</small></div>}</>}
function Answering({seconds,responses,total}:{seconds:number;responses:number;total:number}){const pct=total?Math.min(100,(responses/total)*100):0;return <><div className="stageGlow"/><div className="countdown">{String(seconds).padStart(2,'0')}</div><div className="stageStatus"><h2>¡Coloca la canción!</h2><p>{responses} de {total} respuestas bloqueadas</p><div className="responseProgress"><i style={{width:`${pct}%`}}/></div></div></>}
function Reveal({round,seconds}:{round:NonNullable<NonNullable<ReturnType<typeof useGameState>['state']>['round']>;seconds:number}){const song=round.song!;return <div className="reveal"><div className="cover">{song.image_url?<img src={song.image_url} alt={`Portada de ${song.title}`}/>:<span className="coverFallback">♪</span>}</div><div className="revealInfo"><span className="eyebrow">La respuesta era</span><h1>{song.title}</h1><h2>{song.artist}</h2><span className="yearPill">{song.release_year}</span><div className="answerChips">{round.answers?.map((a,i)=>{const p=Array.isArray(a.player)?a.player[0]:a.player;return <span key={i} className={`answerChip ${a.is_exact?'ok':'bad'}`}>{a.is_exact?<Check size={15}/>:<X size={15}/>} {p?.name??'Jugador'} · Año {a.is_exact?'✓':'✗'} · Título {a.title_correct?'✓':'✗'} {a.total_score>0&&`+${a.total_score}`}</span>})}</div><p style={{color:'var(--muted)'}}>Siguiente ronda en {seconds}s</p></div></div>}
function Finish({state}:{state:NonNullable<ReturnType<typeof useGameState>['state']>}){const r=state.results??[];const top=[r[1],r[0],r[2]];return <div className="gamePage" data-game-theme={state.game.theme} style={{display:'grid',placeItems:'center'}}><div className="finishPodium"><span className="eyebrow">Partida terminada</span><h1>El tiempo tiene dueño.</h1><div className="podium">{top.map((p,i)=>p?<div key={p.user_id} className={`podiumPlace ${i===1?'first':i===0?'second':'third'}`}><span className="emoji">{avatarEmoji(p.avatar_id)}</span><strong>{p.player_name}</strong><small>#{p.rank} · {p.exact_hits} exactas</small><b>{p.score}</b></div>:null)}</div><div style={{marginTop:30}}><Button onClick={()=>location.href='/create'}><Music2/>Crear otra partida</Button></div></div></div>}
function LoadingStage(){return <div className="gamePage" style={{display:'grid',placeItems:'center'}}><div className="record"/></div>}
function ErrorStage({message}:{message:string}){return <div className="gamePage" style={{display:'grid',placeItems:'center'}}><div className="glass" style={{padding:30,textAlign:'center'}}><h1>No pudimos abrir la sala</h1><p>{message}</p><Button onClick={()=>location.href='/'}>Volver al inicio</Button></div></div>}
